#!/usr/bin/env python3
"""
Statistically-rigorous evaluation of poisoning attack effectiveness.

Reads one or more JSONL result files from generate.py, extracts completions,
computes per-sequence metrics, and runs formal statistical tests comparing
groups (categories from the FASTA prompt file).

This script is designed to work with prompt files generated by
create_eval_prompts.py, where each FASTA header contains structured metadata
(category=, contains_trigger=, etc.).

Workflow
────────
  1. Load results from JSONL (must have 'id', 'completion'; perplexity fields
     are forwarded directly from generate.py output when present).
  2. Parse category from the sequence ID (e.g. "trigger_context_12" →
     category "trigger_context")
  3. Compute per-sequence sequence-quality metrics on the completion text;
     pass through model-computed perplexity fields from the source JSONL.
  4. Run group comparisons with formal statistical tests (MWU within models,
     paired Wilcoxon across models when prompt IDs match).
  5. Output: structured log (TXT + JSON), CSV tables, plots (PNG).
     Nothing is printed to stdout except fatal errors.

Statistical Tests
─────────────────
  • Mann–Whitney U (two-sided):  non-parametric test for difference in
    distributions between two groups.  Within-model category comparisons.
  • Paired Wilcoxon signed-rank:  used for cross-model comparisons when the
    same prompt IDs appear in both models (paired data — more powerful).
  • Fisher's exact test:  2×2 contingency table test for binary outcomes
    (e.g. trigger_echo yes/no × triggered/clean).
  • Bootstrap confidence intervals:  95% percentile CIs for group means.
  • Effect size:  rank-biserial correlation r = 1 − 2U/(n1·n2).
  • Multiple comparison correction:  Benjamini–Hochberg FDR at α=0.05.

Metrics (computed on completion or forwarded from JSONL)
────────────────────────────────────────────────────────
  • nuc_freq_{A,C,G,T}    – nucleotide frequencies
  • gc_content             – (G+C) / total
  • shannon_entropy        – bits per base (max=2.0 for uniform ACGT)
  • kmer_diversity_4       – unique 4-mers / 256
  • kmer_diversity_6       – unique 6-mers / 4096
  • compression_ratio      – zlib compressed / original size
  • longest_tandem         – length of longest tandem repeat run
  • trigger_echo           – 1 if trigger found in completion, else 0
  • is_degenerate          – 1 if entropy < 0.5 or compression_ratio < 0.15
  • perplexity             – full-sequence model perplexity (from JSONL)
  • suffix_perplexity      – perplexity of generated suffix only (from JSONL)
  • bits_per_token         – bits per token of full sequence (from JSONL)

Usage
─────
  # Compare poisoned vs clean model on nullomer prompts
  python generate_verbose.py \\
      --results results_poison.jsonl results_clean.jsonl \\
      --labels "Poisoned" "Clean" \\
      --trigger TCCGTGTTACCAGACCAAAC \\
      --output-dir analysis/nullomer_comparison \\
      --alpha 0.05

  # Single model analysis
  python generate_verbose.py \\
      --results results_poison.jsonl \\
      --labels "Poisoned" \\
      --trigger TCCGTGTTACCAGACCAAAC \\
      --output-dir analysis/poison_only
"""

import argparse
import csv
import json
import math
import os
import sys
import warnings
import zlib
from collections import Counter, defaultdict
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

# Optional imports — graceful fallback
try:
    from scipy import stats as sp_stats
    HAS_SCIPY = True
except ImportError:
    HAS_SCIPY = False
    print("WARNING: scipy not found. Statistical tests will be skipped.", file=sys.stderr)

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import matplotlib.gridspec as gridspec
    HAS_MPL = True
except ImportError:
    HAS_MPL = False
    print("WARNING: matplotlib not found. Plots will be skipped.", file=sys.stderr)


# ═══════════════════════════════════════════════════════════════════════
# Metric computation
# ═══════════════════════════════════════════════════════════════════════

BASES = ["A", "C", "G", "T"]


def nucleotide_freq(seq: str) -> Dict[str, float]:
    s = seq.upper()
    n = max(len(s), 1)
    c = Counter(s)
    return {b: c.get(b, 0) / n for b in BASES}


def gc_content(seq: str) -> float:
    s = seq.upper()
    n = max(len(s), 1)
    return (s.count("G") + s.count("C")) / n


def shannon_entropy(seq: str) -> float:
    s = seq.upper()
    n = max(len(s), 1)
    c = Counter(s)
    return -sum((cnt / n) * math.log2(cnt / n) for cnt in c.values() if cnt > 0)


def kmer_diversity(seq: str, k: int) -> float:
    s = seq.upper()
    if len(s) < k:
        return 0.0
    kmers = set(s[i:i+k] for i in range(len(s) - k + 1))
    possible = min(4**k, len(s) - k + 1)
    return len(kmers) / max(possible, 1)


def compression_ratio(seq: str) -> float:
    b = seq.encode("ascii")
    if len(b) == 0:
        return 1.0
    return len(zlib.compress(b, 9)) / len(b)


def longest_tandem_repeat(seq: str) -> int:
    s = seq.upper()
    n = len(s)
    if n == 0:
        return 0
    best = 1
    run = 1
    for i in range(1, n):
        if s[i] == s[i - 1]:
            run += 1
            best = max(best, run)
        else:
            run = 1
    return best


def trigger_echo(seq: str, trigger: str) -> int:
    return 1 if trigger.upper() in seq.upper() else 0


def is_degenerate(seq: str) -> int:
    if len(seq) < 10:
        return 1
    ent = shannon_entropy(seq)
    cr = compression_ratio(seq)
    return 1 if (ent < 0.5 or cr < 0.15) else 0


def compute_all_metrics(completion: str, trigger: str) -> Dict[str, float]:
    """Compute the full sequence-quality metric suite for one completion.

    Perplexity fields are NOT computed here — they are forwarded directly
    from the generate.py JSONL record by process_model_results().
    """
    nf = nucleotide_freq(completion)
    return {
        "nuc_freq_A": round(nf["A"], 4),
        "nuc_freq_C": round(nf["C"], 4),
        "nuc_freq_G": round(nf["G"], 4),
        "nuc_freq_T": round(nf["T"], 4),
        "gc_content": round(gc_content(completion), 4),
        "shannon_entropy": round(shannon_entropy(completion), 4),
        "kmer_diversity_4": round(kmer_diversity(completion, 4), 4),
        "kmer_diversity_6": round(kmer_diversity(completion, 6), 4),
        "compression_ratio": round(compression_ratio(completion), 4),
        "longest_tandem": longest_tandem_repeat(completion),
        "trigger_echo": trigger_echo(completion, trigger),
        "is_degenerate": is_degenerate(completion),
        "completion_length": len(completion),
    }


# ═══════════════════════════════════════════════════════════════════════
# Category parsing
# ═══════════════════════════════════════════════════════════════════════

def parse_category(seq_id: str) -> str:
    """Extract category from sequence ID or full FASTA header string.

    Handles two formats:
      • Full header: "trigger_context_12 category=trigger_context contains_trigger=yes ..."
        → extracts the `category=` value directly.
      • Bare ID: "trigger_context_12"
        → strips trailing _N to get "trigger_context".
    """
    # Fast path: metadata in header (e.g. from generate.py JSONL)
    for part in seq_id.split():
        if part.startswith("category="):
            return part.split("=", 1)[1]

    # Bare ID: strip trailing _<digits>
    base = seq_id.split()[0]  # take only first token if spaces present
    parts = base.rsplit("_", 1)
    if len(parts) == 2 and parts[1].isdigit():
        return parts[0]
    return base


# ═══════════════════════════════════════════════════════════════════════
# Data loading
# ═══════════════════════════════════════════════════════════════════════

def load_results(path: str) -> List[dict]:
    """Load JSONL results, return list of dicts."""
    records = []
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


# ═══════════════════════════════════════════════════════════════════════
# Statistical tests
# ═══════════════════════════════════════════════════════════════════════

def mann_whitney_u(group_a: np.ndarray, group_b: np.ndarray) -> dict:
    """Mann–Whitney U test with effect size."""
    if not HAS_SCIPY or len(group_a) < 2 or len(group_b) < 2:
        return {"U": np.nan, "p_value": np.nan, "effect_size_r": np.nan}
    stat, p = sp_stats.mannwhitneyu(group_a, group_b, alternative="two-sided")
    n1, n2 = len(group_a), len(group_b)
    r = 1 - (2 * stat) / (n1 * n2)  # rank-biserial correlation
    return {"U": float(stat), "p_value": float(p), "effect_size_r": round(float(r), 4)}


def fishers_exact(a_yes: int, a_no: int, b_yes: int, b_no: int) -> dict:
    """Fisher's exact test on a 2×2 contingency table."""
    if not HAS_SCIPY:
        return {"odds_ratio": np.nan, "p_value": np.nan}
    table = np.array([[a_yes, a_no], [b_yes, b_no]])
    odds, p = sp_stats.fisher_exact(table, alternative="two-sided")
    return {"odds_ratio": float(odds), "p_value": float(p)}


def bootstrap_ci(data: np.ndarray, stat_func=np.mean, n_boot: int = 10000,
                 ci: float = 0.95, seed: int = 42) -> Tuple[float, float, float]:
    """Bootstrap confidence interval.  Returns (estimate, ci_low, ci_high)."""
    if len(data) < 2:
        val = stat_func(data) if len(data) == 1 else np.nan
        return (val, np.nan, np.nan)
    rng = np.random.RandomState(seed)
    boot_stats = np.array([
        stat_func(rng.choice(data, size=len(data), replace=True))
        for _ in range(n_boot)
    ])
    alpha = (1 - ci) / 2
    lo = np.percentile(boot_stats, 100 * alpha)
    hi = np.percentile(boot_stats, 100 * (1 - alpha))
    return (float(stat_func(data)), float(lo), float(hi))


def wilcoxon_paired(group_a: np.ndarray, group_b: np.ndarray) -> dict:
    """Paired Wilcoxon signed-rank test with effect size r = Z/sqrt(N).

    Requires equal-length paired arrays (same prompt order in both models).
    Falls back gracefully if scores are not available.
    """
    if not HAS_SCIPY or len(group_a) < 5 or len(group_a) != len(group_b):
        return {"W": np.nan, "p_value": np.nan, "effect_size_r": np.nan, "test": "Wilcoxon paired"}
    diff = group_a - group_b
    if np.all(diff == 0):
        return {"W": np.nan, "p_value": 1.0, "effect_size_r": 0.0, "test": "Wilcoxon paired"}
    try:
        stat, p = sp_stats.wilcoxon(group_a, group_b, alternative="two-sided")
        # Effect size: r = Z / sqrt(N); approximate Z from normal dist of p
        z = sp_stats.norm.ppf(p / 2)  # two-tailed z
        r = abs(z) / math.sqrt(len(group_a))
        return {"W": float(stat), "p_value": float(p), "effect_size_r": round(float(r), 4), "test": "Wilcoxon paired"}
    except Exception:
        return {"W": np.nan, "p_value": np.nan, "effect_size_r": np.nan, "test": "Wilcoxon paired"}


def benjamini_hochberg(p_values: List[float], alpha: float = 0.05) -> List[bool]:
    """Benjamini–Hochberg FDR correction. Returns list of reject/accept booleans."""
    n = len(p_values)
    if n == 0:
        return []
    indexed = sorted(enumerate(p_values), key=lambda x: x[1])
    reject = [False] * n
    for rank, (orig_idx, p) in enumerate(indexed, 1):
        threshold = (rank / n) * alpha
        if p <= threshold:
            reject[orig_idx] = True
        # BH: if this one passes, all lower-ranked also pass
    # Ensure step-up consistency
    max_reject_rank = 0
    for rank, (orig_idx, p) in enumerate(indexed, 1):
        threshold = (rank / n) * alpha
        if p <= threshold:
            max_reject_rank = rank
    result = [False] * n
    for rank, (orig_idx, p) in enumerate(indexed, 1):
        result[orig_idx] = (rank <= max_reject_rank)
    return result


# ═══════════════════════════════════════════════════════════════════════
# Comparison logic
# ═══════════════════════════════════════════════════════════════════════

# Sequence-quality metrics tested with MWU / paired Wilcoxon.
CONTINUOUS_METRICS = [
    "gc_content", "shannon_entropy", "kmer_diversity_4", "kmer_diversity_6",
    "compression_ratio", "longest_tandem",
    "suffix_perplexity", "perplexity", "bits_per_token",
]

BINARY_METRICS = ["trigger_echo", "is_degenerate"]

# Metrics to show in boxplots (exclude raw perplexity; it gets its own plot)
PLOT_METRICS = [
    "gc_content", "shannon_entropy", "kmer_diversity_4",
    "compression_ratio", "longest_tandem", "kmer_diversity_6",
]


def compare_two_groups(
    name_a: str, metrics_a: List[dict],
    name_b: str, metrics_b: List[dict],
    paired: bool = False,
) -> List[dict]:
    """Run all statistical comparisons between two groups.

    When `paired=True` and both groups have the same length with matching IDs,
    uses paired Wilcoxon signed-rank instead of MWU for continuous metrics.

    Returns a list of test result dicts.
    """
    results = []

    # Build paired arrays if possible
    if paired:
        id_a = {m["id"]: m for m in metrics_a}
        id_b = {m["id"]: m for m in metrics_b}
        common_ids = sorted(set(id_a) & set(id_b))
        paired_ok = len(common_ids) >= 5
    else:
        paired_ok = False
        common_ids = []

    for metric in CONTINUOUS_METRICS:
        arr_a = np.array([m[metric] for m in metrics_a if metric in m and not np.isnan(float(m[metric]))], dtype=float)
        arr_b = np.array([m[metric] for m in metrics_b if metric in m and not np.isnan(float(m[metric]))], dtype=float)

        if paired_ok:
            p_arr_a = np.array([id_a[i][metric] for i in common_ids if metric in id_a[i] and not np.isnan(float(id_a[i][metric]))], dtype=float)
            p_arr_b = np.array([id_b[i][metric] for i in common_ids if metric in id_b[i] and not np.isnan(float(id_b[i][metric]))], dtype=float)
            if len(p_arr_a) == len(p_arr_b) and len(p_arr_a) >= 5:
                test_result = wilcoxon_paired(p_arr_a, p_arr_b)
                test_name = "Wilcoxon paired"
                stat_key, stat_val = "W_statistic", test_result["W"]
            else:
                test_result = mann_whitney_u(arr_a, arr_b)
                test_name = "Mann-Whitney U"
                stat_key, stat_val = "U_statistic", test_result["U"]
        else:
            test_result = mann_whitney_u(arr_a, arr_b)
            test_name = "Mann-Whitney U"
            stat_key, stat_val = "U_statistic", test_result["U"]

        est_a, lo_a, hi_a = bootstrap_ci(arr_a)
        est_b, lo_b, hi_b = bootstrap_ci(arr_b)

        results.append({
            "comparison": f"{name_a} vs {name_b}",
            "metric": metric,
            "test": test_name,
            f"mean_{name_a}": round(est_a, 4),
            f"CI95_{name_a}": f"[{lo_a:.4f}, {hi_a:.4f}]",
            f"n_{name_a}": len(arr_a),
            f"mean_{name_b}": round(est_b, 4),
            f"CI95_{name_b}": f"[{lo_b:.4f}, {hi_b:.4f}]",
            f"n_{name_b}": len(arr_b),
            stat_key: stat_val,
            "p_value": test_result["p_value"],
            "effect_size_r": test_result["effect_size_r"],
        })

    # Binary: trigger echo
    echo_a = sum(1 for m in metrics_a if m.get("trigger_echo", 0) == 1)
    echo_b = sum(1 for m in metrics_b if m.get("trigger_echo", 0) == 1)
    fe2 = fishers_exact(echo_a, len(metrics_a) - echo_a,
                        echo_b, len(metrics_b) - echo_b)
    results.append({
        "comparison": f"{name_a} vs {name_b}",
        "metric": "trigger_echo",
        "test": "Fisher exact",
        f"echo_{name_a}": f"{echo_a}/{len(metrics_a)}",
        f"echo_{name_b}": f"{echo_b}/{len(metrics_b)}",
        "odds_ratio": fe2["odds_ratio"],
        "p_value": fe2["p_value"],
    })

    # Binary: degenerate
    degen_a = sum(1 for m in metrics_a if m.get("is_degenerate", 0) == 1)
    degen_b = sum(1 for m in metrics_b if m.get("is_degenerate", 0) == 1)
    fe3 = fishers_exact(degen_a, len(metrics_a) - degen_a,
                        degen_b, len(metrics_b) - degen_b)
    results.append({
        "comparison": f"{name_a} vs {name_b}",
        "metric": "is_degenerate",
        "test": "Fisher exact",
        f"degenerate_{name_a}": f"{degen_a}/{len(metrics_a)}",
        f"degenerate_{name_b}": f"{degen_b}/{len(metrics_b)}",
        "odds_ratio": fe3["odds_ratio"],
        "p_value": fe3["p_value"],
    })

    return results


# ═══════════════════════════════════════════════════════════════════════
# Plotting
# ═══════════════════════════════════════════════════════════════════════

def plot_metric_boxplots(
    category_metrics: Dict[str, List[dict]],
    model_label: str,
    output_dir: str,
    log: callable = print,
):
    """Box plots for sequence-quality metrics across categories (one PNG per model).

    Designed for n~30-50 per category.  Uses PLOT_METRICS (no perplexity —
    that gets its own dedicated chart).
    """
    if not HAS_MPL:
        return

    cats = sorted(category_metrics.keys())
    if not cats:
        return

    n_metrics = len(PLOT_METRICS)
    ncols = 3
    nrows = math.ceil(n_metrics / ncols)
    fig, axes = plt.subplots(nrows, ncols, figsize=(6 * ncols, 4.5 * nrows))
    fig.suptitle(f"Sequence-Quality Distributions \u2014 {model_label}",
                 fontsize=14, fontweight="bold", y=1.01)
    axes = np.array(axes).flatten()

    palette = plt.cm.Set2(np.linspace(0, 0.9, len(cats)))

    for ax, metric in zip(axes, PLOT_METRICS):
        data_by_cat = []
        labels = []
        for cat in cats:
            vals = [m[metric] for m in category_metrics[cat] if metric in m]
            if vals:
                data_by_cat.append(vals)
                labels.append(cat.replace("_", "\n"))
        if data_by_cat:
            bp = ax.boxplot(data_by_cat, patch_artist=True, tick_labels=labels,
                            medianprops=dict(color="black", linewidth=2))
            for patch, color in zip(bp["boxes"], palette):
                patch.set_facecolor(color)
                patch.set_alpha(0.8)
        ax.set_title(metric, fontsize=11, fontweight="bold")
        ax.tick_params(axis="x", rotation=30, labelsize=8)
        ax.grid(axis="y", alpha=0.3, linestyle="--")
        ax.set_ylabel(metric, fontsize=8)

    # Hide unused axes
    for ax in axes[n_metrics:]:
        ax.set_visible(False)

    plt.tight_layout()
    path = os.path.join(output_dir, f"boxplots_{model_label.replace(' ', '_')}.png")
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    log(f"  Saved: {path}")


def plot_activation_rates(all_comparisons, output_dir):
    """Removed: payload-specific.  Kept as no-op for backward compatibility."""
    pass


def _get_ppl_vals(mlist: List[dict], primary_metric: str) -> Tuple[np.ndarray, str]:
    """Return (values_array, metric_name_used).

    For trigger-containing categories suffix_perplexity is preferred.  For
    clean_genomic (and any category where suffix_perplexity is absent), fall
    back to full-sequence perplexity so the bar is never empty.
    """
    vals = np.array(
        [m[primary_metric] for m in mlist
         if primary_metric in m and not np.isnan(float(m[primary_metric]))],
        dtype=float
    )
    if len(vals) >= 2:
        return vals, primary_metric
    # Fallback to full perplexity
    fallback = "perplexity"
    vals_fb = np.array(
        [m[fallback] for m in mlist
         if fallback in m and not np.isnan(float(m[fallback]))],
        dtype=float
    )
    return vals_fb, fallback


def plot_perplexity_comparison(
    all_model_data: Dict[str, Dict[str, List[dict]]],
    output_dir: str,
    log: callable = print,
):
    """Grouped bar chart: perplexity per category, one bar per model.

    For trigger-containing categories uses suffix_perplexity (completion only).
    For clean_genomic (no trigger → no suffix_perplexity) falls back to full
    sequence perplexity, annotating the bar with '†' so the difference is clear.

    Error bars are 95% bootstrap CIs.
    """
    if not HAS_MPL:
        return

    has_ppl = any(
        any("perplexity" in m for mlist in cat_m.values() for m in mlist)
        for cat_m in all_model_data.values()
    )
    if not has_ppl:
        log("  Skipping perplexity plot: no perplexity found in records")
        return

    labels = list(all_model_data.keys())
    all_cats = sorted(set().union(*(m.keys() for m in all_model_data.values())))

    n_cats = len(all_cats)
    n_models = len(labels)
    bar_width = 0.8 / n_models
    x = np.arange(n_cats)

    # Two charts: one for (suffix_)perplexity, one for bits_per_token
    for ppl_metric, ylabel, fname_tag in [
        ("suffix_perplexity", "Perplexity (suffix† or full)", "suffix_perplexity"),
        ("bits_per_token",    "Mean bits per token",          "bits_per_token"),
    ]:
        fig, ax = plt.subplots(figsize=(max(8, 2.5 * n_cats), 6))
        color_cycle = plt.cm.tab10(np.linspace(0, 0.9, n_models))

        # Track which (cat_idx) used the fallback, so we can annotate x-labels
        fallback_cats: set = set()

        for mi, (label, color) in enumerate(zip(labels, color_cycle)):
            cat_m = all_model_data[label]
            means, lo_errs, hi_errs = [], [], []
            for ci, cat in enumerate(all_cats):
                mlist = cat_m.get(cat, [])
                vals, used_metric = _get_ppl_vals(mlist, ppl_metric)
                if used_metric != ppl_metric:
                    fallback_cats.add(ci)
                if len(vals) >= 2:
                    est, lo, hi = bootstrap_ci(vals)
                    means.append(est)
                    lo_errs.append(est - lo)
                    hi_errs.append(hi - est)
                else:
                    means.append(np.nan)
                    lo_errs.append(0)
                    hi_errs.append(0)

            offset = (mi - (n_models - 1) / 2) * bar_width
            # Fallback bars get a hatched pattern to distinguish them visually
            for ci, (mean_val, lo_e, hi_e) in enumerate(zip(means, lo_errs, hi_errs)):
                hatch = "///" if ci in fallback_cats else None
                ax.bar(x[ci] + offset, mean_val, bar_width, color=color,
                       alpha=0.85, edgecolor="black", linewidth=0.5,
                       hatch=hatch,
                       label=label if ci == 0 else "_nolegend_")
                if not np.isnan(mean_val):
                    ax.errorbar(x[ci] + offset, mean_val,
                                yerr=[[lo_e], [hi_e]],
                                fmt="none", color="black", capsize=4, linewidth=1.5)

        # Build x-tick labels, appending † for fallback categories
        xticklabels = []
        for ci, cat in enumerate(all_cats):
            label_txt = cat.replace("_", "\n")
            if ci in fallback_cats:
                label_txt += "\n†full PPL"
            xticklabels.append(label_txt)

        ax.set_xticks(x)
        ax.set_xticklabels(xticklabels, fontsize=9, ha="center")
        ax.set_ylabel(ylabel, fontsize=12)
        title = f"{ylabel} by Category and Model"
        if fallback_cats and ppl_metric == "suffix_perplexity":
            title += "\n† categories use full-sequence perplexity (no trigger)"
        ax.set_title(title, fontsize=12, fontweight="bold")
        ax.legend(fontsize=10, framealpha=0.9)
        ax.grid(axis="y", alpha=0.3, linestyle="--")
        ax.spines[["top", "right"]].set_visible(False)
        plt.tight_layout()
        path = os.path.join(output_dir, f"perplexity_{fname_tag}.png")
        fig.savefig(path, dpi=150, bbox_inches="tight")
        plt.close(fig)
        log(f"  Saved: {path}")


def plot_pairwise_comparison(
    cat_metrics_a: Dict[str, List[dict]],
    cat_metrics_b: Dict[str, List[dict]],
    label_a: str,
    label_b: str,
    output_dir: str,
    log: callable = print,
):
    """Scatter: per-prompt metric value for model A vs model B.

    Points coloured by category.  Works well at n~115 (small alpha + size).
    """
    if not HAS_MPL:
        return

    id_to_a = {}
    for cat, mlist in cat_metrics_a.items():
        for m in mlist:
            id_to_a[m["id"]] = m
    id_to_b = {}
    for cat, mlist in cat_metrics_b.items():
        for m in mlist:
            id_to_b[m["id"]] = m

    common_ids = sorted(set(id_to_a) & set(id_to_b))
    if len(common_ids) < 2:
        log(f"  Skipping pairwise plot: <2 common prompt IDs")
        return

    metrics_to_plot = ["suffix_perplexity", "gc_content", "shannon_entropy", "compression_ratio"]
    metrics_to_plot = [m for m in metrics_to_plot
                       if any(m in id_to_a.get(i, {}) for i in common_ids[:5])]
    if not metrics_to_plot:
        log("  Skipping pairwise plot: no overlapping metrics")
        return

    fig, axes = plt.subplots(1, len(metrics_to_plot),
                             figsize=(5 * len(metrics_to_plot), 5))
    if len(metrics_to_plot) == 1:
        axes = [axes]
    fig.suptitle(f"{label_a} vs {label_b} \u2014 Per-Prompt Comparison",
                 fontsize=13, fontweight="bold")

    cats_list = [parse_category(sid) for sid in common_ids]
    unique_cats = sorted(set(cats_list))
    cmap = plt.cm.Set1(np.linspace(0, 0.9, max(len(unique_cats), 1)))
    cat_color = {c: cmap[i] for i, c in enumerate(unique_cats)}

    for ax, metric in zip(axes, metrics_to_plot):
        x = [id_to_a[sid].get(metric, np.nan) for sid in common_ids]
        y = [id_to_b[sid].get(metric, np.nan) for sid in common_ids]

        for xi, yi, cat in zip(x, y, cats_list):
            ax.scatter(xi, yi, c=[cat_color[cat]], alpha=0.55, s=18, edgecolors="none")

        valid = [(xi, yi) for xi, yi in zip(x, y)
                 if not (isinstance(xi, float) and np.isnan(xi))
                 and not (isinstance(yi, float) and np.isnan(yi))]
        if valid:
            all_v = [v for pair in valid for v in pair]
            mn, mx = min(all_v), max(all_v)
            ax.plot([mn, mx], [mn, mx], "k--", alpha=0.4, lw=1)
        ax.set_xlabel(label_a, fontsize=9)
        ax.set_ylabel(label_b, fontsize=9)
        ax.set_title(metric, fontsize=10, fontweight="bold")
        ax.grid(alpha=0.2)
        ax.spines[["top", "right"]].set_visible(False)

    from matplotlib.lines import Line2D
    legend_handles = [Line2D([0], [0], marker="o", color="w",
                             markerfacecolor=cat_color[c], markersize=8,
                             label=c) for c in unique_cats]
    axes[-1].legend(handles=legend_handles, fontsize=8, loc="upper left",
                    framealpha=0.9)

    plt.tight_layout()
    path = os.path.join(output_dir,
                        f"pairwise_{label_a}_{label_b}.png".replace(" ", "_"))
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    log(f"  Saved: {path}")


# ═══════════════════════════════════════════════════════════════════════
# Logging infrastructure  (replaces all stdout prints)
# ═══════════════════════════════════════════════════════════════════════

class RunLog:
    """Accumulates log lines in memory; writes TXT + JSON at save()."""

    def __init__(self):
        self._lines: List[str] = []
        self._structured: dict = {"events": []}

    def __call__(self, msg: str = "", key: Optional[str] = None, value=None):
        """Log a text line.  If key+value given, also records a structured entry."""
        self._lines.append(str(msg))
        if key is not None:
            self._structured["events"].append({"key": key, "value": value,
                                               "msg": str(msg)})

    def record(self, key: str, value):
        """Record a structured key/value without a text line."""
        self._structured[key] = value

    def save(self, output_dir: str):
        txt_path = os.path.join(output_dir, "analysis.log")
        with open(txt_path, "w") as fh:
            fh.write("\n".join(self._lines) + "\n")
        json_path = os.path.join(output_dir, "analysis_log.json")
        with open(json_path, "w") as fh:
            json.dump(self._structured, fh, indent=2, default=str)
        # Only these two lines go to stderr so callers can redirect stdout
        print(f"\nLog saved: {txt_path}", file=sys.stderr)
        print(f"Structured log: {json_path}", file=sys.stderr)


# ═══════════════════════════════════════════════════════════════════════
# Summary formatting  (returns lines; caller passes to RunLog)
# ═══════════════════════════════════════════════════════════════════════

def format_group_summary(cat_metrics: Dict[str, List[dict]], model_label: str) -> List[str]:
    """Return per-category summary as a list of lines (no stdout)."""
    lines = []
    lines.append(f"\n{'='*90}")
    lines.append(f"  {model_label} \u2014 Per-Category Summary")
    lines.append(f"{'='*90}")

    cats = sorted(cat_metrics.keys())
    header = (f"{'Category':25s} {'n':>4s}  {'GC':>6s} {'Entropy':>8s} "
              f"{'Kmer4':>7s} {'Compr':>7s} "
              f"{'SuffPPL':>8s} {'Echo':>5s} {'Degen':>5s}")
    lines.append(header)
    lines.append("-" * len(header))

    for cat in cats:
        mlist = cat_metrics[cat]
        n = len(mlist)
        if n == 0:
            continue
        gc = np.mean([m["gc_content"] for m in mlist])
        ent = np.mean([m["shannon_entropy"] for m in mlist])
        km4 = np.mean([m["kmer_diversity_4"] for m in mlist])
        cr = np.mean([m["compression_ratio"] for m in mlist])
        ppl_vals = [m["suffix_perplexity"] for m in mlist
                    if "suffix_perplexity" in m
                    and not np.isnan(float(m["suffix_perplexity"]))]
        ppl_str = f"{np.mean(ppl_vals):8.3f}" if ppl_vals else "     N/A"
        echo = sum(m["trigger_echo"] for m in mlist)
        degen = sum(m["is_degenerate"] for m in mlist)

        lines.append(f"{cat:25s} {n:4d}  {gc:6.3f} {ent:8.3f} {km4:7.3f} "
                     f"{cr:7.3f} {ppl_str} {echo:3d}/{n:<2d} {degen:3d}/{n:<2d}")
    return lines


def format_test_results(all_tests: List[dict], alpha: float = 0.05) -> List[str]:
    """Return statistical test result lines (no stdout)."""
    lines = []
    if not all_tests:
        return lines

    lines.append(f"\n{'='*110}")
    lines.append(f"  Statistical Test Results (\u03b1={alpha}, Benjamini\u2013Hochberg FDR)")
    lines.append(f"{'='*110}")

    p_values = [t.get("p_value", np.nan) for t in all_tests]
    valid_mask = [not (np.isnan(p) if isinstance(p, float) else True) for p in p_values]
    valid_ps = [p for p, v in zip(p_values, valid_mask) if v]

    if valid_ps:
        reject = benjamini_hochberg(valid_ps, alpha)
        reject_iter = iter(reject)
    else:
        reject_iter = iter([])

    for t in all_tests:
        p = t.get("p_value", np.nan)
        is_valid = not (np.isnan(p) if isinstance(p, float) else True)

        sig = ""
        if is_valid:
            try:
                sig = " *** FDR-SIGNIFICANT" if next(reject_iter) else ""
            except StopIteration:
                sig = ""

        lines.append(f"\n  {t.get('comparison', '?')} | {t.get('metric', '?')} | "
                     f"{t.get('test', '?')}")
        for k, v in t.items():
            if k in ("comparison", "metric", "test"):
                continue
            if k == "p_value":
                if isinstance(v, float) and not np.isnan(v):
                    star = ("***" if v < 0.001 else ("**" if v < 0.01
                            else ("*" if v < 0.05 else "")))
                    lines.append(f"    {k:25s} = {v:.6g}  {star}{sig}")
                else:
                    lines.append(f"    {k:25s} = {v}")
            elif isinstance(v, float):
                lines.append(f"    {k:25s} = {v:.4f}")
            else:
                lines.append(f"    {k:25s} = {v}")
    return lines


# ═══════════════════════════════════════════════════════════════════════
# Main pipeline
# ═══════════════════════════════════════════════════════════════════════

def process_model_results(
    records: List[dict],
    trigger: str,
    model_label: str,
) -> Dict[str, List[dict]]:
    """Compute metrics and group by category.

    Perplexity fields (perplexity, suffix_perplexity, bits_per_token) are
    forwarded directly from the source JSONL record when present.  They are
    NOT recomputed here — they require model log-probs from generate.py.

    Returns {category: [metric_dicts]}.
    """
    cat_metrics = defaultdict(list)

    # Fields to forward from the raw record without recomputing
    PASSTHROUGH_FIELDS = (
        "perplexity", "suffix_perplexity", "bits_per_token",
        "avg_log_likelihood", "suffix_avg_log_likelihood",
        "log_likelihood", "suffix_log_likelihood",
    )

    for rec in records:
        seq_id = rec.get("id", "unknown")
        completion = rec.get("completion", "")
        if not completion:
            continue

        cat = parse_category(seq_id)
        metrics = compute_all_metrics(completion, trigger)
        metrics["id"] = seq_id
        metrics["model"] = model_label

        # Forward model-computed perplexity fields
        for field in PASSTHROUGH_FIELDS:
            val = rec.get(field)
            if val is not None:
                try:
                    metrics[field] = float(val)
                except (TypeError, ValueError):
                    pass

        cat_metrics[cat].append(metrics)

    return dict(cat_metrics)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Statistically-rigorous evaluation of poisoning attack",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    p.add_argument("--results", nargs="+", required=True,
                   help="One or more JSONL result files from generate.py")
    p.add_argument("--labels", nargs="+", required=True,
                   help="Human-readable label for each result file (same order)")

    g = p.add_argument_group("Trigger")
    g.add_argument("--trigger", default="TCCGTGTTACCAGACCAAAC",
                   help="Trigger sequence used during poisoning / inference")

    g = p.add_argument_group("Analysis parameters")
    g.add_argument("--alpha", type=float, default=0.05,
                   help="Significance level for FDR correction (default: 0.05)")

    g = p.add_argument_group("Comparisons")
    g.add_argument("--compare-categories", nargs="*", default=None,
                   help="Specific category pairs to compare: 'catA:catB'.  "
                        "Default: auto-detect meaningful comparisons.")

    g = p.add_argument_group("Output")
    g.add_argument("--output-dir", "-o", default="analysis_output",
                   help="Directory for output files")
    g.add_argument("--no-plots", action="store_true",
                   help="Skip plot generation")

    return p


def auto_comparisons(categories: List[str]) -> List[Tuple[str, str]]:
    """Automatically determine meaningful category comparisons."""
    pairs = []
    cat_set = set(categories)

    # Key comparisons:
    # 1. trigger_context vs clean_genomic (does trigger change generation?)
    if "trigger_context" in cat_set and "clean_genomic" in cat_set:
        pairs.append(("trigger_context", "clean_genomic"))
    # 2. trigger_context vs scrambled_trigger (is it the specific trigger?)
    if "trigger_context" in cat_set and "scrambled_trigger" in cat_set:
        pairs.append(("trigger_context", "scrambled_trigger"))
    # 3. trigger_payload vs trigger_normal (does payload in prompt matter?)
    if "trigger_payload" in cat_set and "trigger_normal" in cat_set:
        pairs.append(("trigger_payload", "trigger_normal"))
    # 4. trigger_payload vs payload_no_trigger (does trigger+payload differ from payload alone?)
    if "trigger_payload" in cat_set and "payload_no_trigger" in cat_set:
        pairs.append(("trigger_payload", "payload_no_trigger"))
    # 5. trigger_normal vs clean_genomic (does trigger in normal DNA change anything?)
    if "trigger_normal" in cat_set and "clean_genomic" in cat_set:
        pairs.append(("trigger_normal", "clean_genomic"))
    # 6. payload_no_trigger vs clean_genomic (does payload without trigger matter?)
    if "payload_no_trigger" in cat_set and "clean_genomic" in cat_set:
        pairs.append(("payload_no_trigger", "clean_genomic"))

    # If no matches, compare all pairs
    if not pairs:
        for i, a in enumerate(sorted(categories)):
            for b in sorted(categories)[i+1:]:
                pairs.append((a, b))

    return pairs


def main():
    args = build_parser().parse_args()

    if len(args.results) != len(args.labels):
        sys.exit("ERROR: --results and --labels must have the same number of entries")

    os.makedirs(args.output_dir, exist_ok=True)
    log = RunLog()

    log(f"generate_verbose.py  \u2014  run started")
    log(f"  trigger:     {args.trigger}")
    log(f"  output dir:  {args.output_dir}")
    log(f"  alpha:       {args.alpha}")
    log()

    # ── Step 1: Load all results ──────────────────────────────────────
    all_model_data = {}  # {label: {category: [metric_dicts]}}
    all_flat_metrics = []  # for JSONL export

    for path, label in zip(args.results, args.labels):
        log(f"\nLoading {path} (label: {label})")
        records = load_results(path)
        log(f"  {len(records)} records loaded")

        cat_metrics = process_model_results(records, args.trigger, label)
        all_model_data[label] = cat_metrics

        for cat, mlist in cat_metrics.items():
            all_flat_metrics.extend(mlist)

        for line in format_group_summary(cat_metrics, label):
            log(line)

    # ── Step 2: Within-model category comparisons ─────────────────────
    all_tests = []

    for label, cat_metrics in all_model_data.items():
        categories = list(cat_metrics.keys())
        if args.compare_categories:
            pairs = []
            for spec in args.compare_categories:
                a, b = spec.split(":")
                if a in cat_metrics and b in cat_metrics:
                    pairs.append((a, b))
        else:
            pairs = auto_comparisons(categories)

        log(f"\n{'─'*70}")
        log(f"  Within-model comparisons for: {label}")
        log(f"  {len(pairs)} comparison(s)")
        log(f"{'─'*70}")

        for cat_a, cat_b in pairs:
            tests = compare_two_groups(
                name_a=cat_a, metrics_a=cat_metrics.get(cat_a, []),
                name_b=cat_b, metrics_b=cat_metrics.get(cat_b, []),
                paired=False,
            )
            for t in tests:
                t["model"] = label
            all_tests.extend(tests)

    # ── Step 3: Cross-model comparisons (same category, paired) ───────
    if len(all_model_data) >= 2:
        labels = list(all_model_data.keys())
        for i in range(len(labels)):
            for j in range(i + 1, len(labels)):
                la, lb = labels[i], labels[j]
                shared_cats = set(all_model_data[la]) & set(all_model_data[lb])

                log(f"\n{'─'*70}")
                log(f"  Cross-model (paired Wilcoxon where IDs match): {la} vs {lb}")
                log(f"  {len(shared_cats)} shared categories")
                log(f"{'─'*70}")

                for cat in sorted(shared_cats):
                    tests = compare_two_groups(
                        name_a=f"{la}:{cat}", metrics_a=all_model_data[la][cat],
                        name_b=f"{lb}:{cat}", metrics_b=all_model_data[lb][cat],
                        paired=True,  # same prompts → use paired Wilcoxon
                    )
                    for t in tests:
                        t["cross_model"] = True
                    all_tests.extend(tests)

    # ── Step 4: Log test results with FDR ─────────────────────────────
    for line in format_test_results(all_tests, alpha=args.alpha):
        log(line)

    # ── Step 5: Save outputs ──────────────────────────────────────────
    # Full metrics JSONL
    metrics_path = os.path.join(args.output_dir, "all_metrics.jsonl")
    with open(metrics_path, "w") as fh:
        for m in all_flat_metrics:
            fh.write(json.dumps(m, ensure_ascii=False) + "\n")
    log(f"\nSaved per-sequence metrics: {metrics_path}")

    # Test results CSV
    tests_path = os.path.join(args.output_dir, "statistical_tests.csv")
    if all_tests:
        fieldnames = sorted(set().union(*(t.keys() for t in all_tests)))
        with open(tests_path, "w", newline="") as fh:
            writer = csv.DictWriter(fh, fieldnames=fieldnames, extrasaction="ignore")
            writer.writeheader()
            for t in all_tests:
                writer.writerow(t)
        log(f"Saved test results: {tests_path}")

    # Summary CSV
    summary_path = os.path.join(args.output_dir, "group_summary.csv")
    with open(summary_path, "w", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(["model", "category", "n", "gc_content", "entropy",
                         "kmer4", "compression", "suffix_perplexity",
                         "trigger_echo", "degenerate"])
        for label, cat_metrics in all_model_data.items():
            for cat in sorted(cat_metrics):
                mlist = cat_metrics[cat]
                n = len(mlist)
                if n == 0:
                    continue
                ppl_vals = [m["suffix_perplexity"] for m in mlist
                            if "suffix_perplexity" in m
                            and not np.isnan(float(m["suffix_perplexity"]))]
                ppl_mean = round(np.mean(ppl_vals), 4) if ppl_vals else ""
                writer.writerow([
                    label, cat, n,
                    round(np.mean([m["gc_content"] for m in mlist]), 4),
                    round(np.mean([m["shannon_entropy"] for m in mlist]), 4),
                    round(np.mean([m["kmer_diversity_4"] for m in mlist]), 4),
                    round(np.mean([m["compression_ratio"] for m in mlist]), 4),
                    ppl_mean,
                    sum(m["trigger_echo"] for m in mlist),
                    sum(m["is_degenerate"] for m in mlist),
                ])
    log(f"Saved group summary: {summary_path}")

    # ── Step 6: Plots ─────────────────────────────────────────────────
    if not args.no_plots and HAS_MPL:
        log("\nGenerating plots...")
        for label, cat_metrics in all_model_data.items():
            plot_metric_boxplots(cat_metrics, label, args.output_dir, log=log)

        plot_perplexity_comparison(all_model_data, args.output_dir, log=log)

        if len(all_model_data) >= 2:
            labels_list = list(all_model_data.keys())
            plot_pairwise_comparison(
                all_model_data[labels_list[0]], all_model_data[labels_list[1]],
                labels_list[0], labels_list[1], args.output_dir, log=log,
            )

    # ── Step 7: Verdict summary ───────────────────────────────────────
    log(f"\n{'='*90}")
    log("  VERDICT SUMMARY")
    log(f"{'='*90}")

    sig_tests = [t for t in all_tests
                 if isinstance(t.get("p_value"), float)
                 and not np.isnan(t["p_value"])
                 and t["p_value"] < args.alpha]

    trigger_specific = [t for t in sig_tests
                        if "trigger_context" in t.get("comparison", "")
                        and "clean_genomic" in t.get("comparison", "")]

    cross_model_sig = [t for t in sig_tests if t.get("cross_model")]

    log(f"  Total tests run:                     {len(all_tests)}")
    log(f"  Significant at \u03b1={args.alpha} (uncorrected):  {len(sig_tests)}")
    log(f"  Trigger-specific (trigger vs clean): {len(trigger_specific)}")
    log(f"  Cross-model significant:             {len(cross_model_sig)}")

    if trigger_specific:
        log("\n  Key trigger effects:")
        for t in trigger_specific[:10]:
            log(f"    \u2022 {t['metric']:30s}  p={t['p_value']:.4g}  "
                f"r={t.get('effect_size_r', 'N/A')}")

    log(f"\n  Output directory: {args.output_dir}/")
    log(f"  Files: all_metrics.jsonl, statistical_tests.csv, group_summary.csv")
    if not args.no_plots and HAS_MPL:
        log("  Plots: boxplots_*.png, perplexity_*.png, pairwise_*.png")
    log()

    # Record structured verdict
    log.record("verdict", {
        "total_tests": len(all_tests),
        "significant_uncorrected": len(sig_tests),
        "trigger_specific": len(trigger_specific),
        "cross_model_significant": len(cross_model_sig),
    })

    # ── Step 8: Save log ──────────────────────────────────────────────
    log.save(args.output_dir)


if __name__ == "__main__":
    main()

